export const seoul = [
  { id: 1, name: "강남구" },
  { id: 2, name: "강동구" },
  { id: 3, name: "강북구" },
  { id: 4, name: "강서구" },
  { id: 5, name: "관악구" },
  { id: 6, name: "광진구" },
  { id: 7, name: "구로구" },
  { id: 8, name: "금천구" },
  { id: 9, name: "노원구" },
  { id: 10, name: "도봉구" },
  { id: 11, name: "동대문구" },
  { id: 12, name: "동작구" },
  { id: 13, name: "마포구" },
  { id: 14, name: "서대문구" },
  { id: 15, name: "서초구" },
  { id: 16, name: "성동구" },
  { id: 17, name: "성북구" },
  { id: 18, name: "송파구" },
  { id: 19, name: "양천구" },
  { id: 20, name: "영등포구" },
  { id: 21, name: "용산구" },
  { id: 22, name: "은평구" },
  { id: 23, name: "종로구" },
  { id: 24, name: "중구" },
  { id: 25, name: "중랑구" },
];

export const houses = [
  {
    title: "논현동 역세권 쉐하",
    houseID: 1,
    placeID: 1,
    placeName: "강남구",
    place: "서울시 강남구 논현동 34-2",
    gender: "여성전용",
    deposit: 100,
    rent: 35,
  },
  {
    title: "신림역 역세권 쉐하",
    houseID: 2,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 신림동 626-65",
    gender: "남성전용",
    deposit: 200,
    rent: 45,
  },
  {
    title: "함께살아요",
    houseID: 3,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 신림로58길 62-5",
    gender: "여성전용",
    deposit: 150,
    rent: 32,
  },
  {
    title: "대학생 환영!",
    houseID: 4,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 청룡길 78",
    gender: "남성전용",
    deposit: 120,
    rent: 40,
  },
  {
    title: "홍대 근처 직장인 쉐하",
    houseID: 5,
    placeID: 13,
    placeName: "마포구",
    place: "서울시 마포구 월드컵북로 31",
    gender: "여성전용",
    deposit: 110,
    rent: 25,
  },
  {
    title: "외국인도 거주가능!",
    houseID: 6,
    placeID: 13,
    placeName: "마포구",
    place: "서울시 마포구 독막로6길 14",
    gender: "남성전용",
    deposit: 170,
    rent: 17,
  },
  {
    title: "스프레틱스지롱",
    houseID: 7,
    placeID: 13,
    placeName: "마포구",
    place: "서울시 마포구 숭문4길 6",
    gender: "여성전용",
    deposit: 300,
    rent: 50,
  },
  {
    title: "살기좋은 후암동 하메구함",
    houseID: 8,
    placeID: 21,
    placeName: "용산구",
    place: "서울시 후암로 20",
    gender: "남성전용",
    deposit: 500,
    rent: 25,
  },
  // {
  //   title: "신림역 역세권 쉐하",
  //   houseID: 2,
  //   placeID: 5,
  //   placeName: "관악구",
  //   place: "서울시 관악구 신림동 626-65",
  //   gender: "남성전용",
  // },
  // {
  //   title: "신림역 역세권 쉐하",
  //   houseID: 2,
  //   placeID: 5,
  //   placeName: "관악구",
  //   place: "서울시 관악구 신림동 626-65",
  //   gender: "남성전용",
  // },
];
