export const seoul = [
  { id: 1, name: "강남구" },
  { id: 2, name: "강동구" },
  { id: 3, name: "강북구" },
  { id: 4, name: "강서구" },
  { id: 5, name: "관악구" },
  { id: 6, name: "광진구" },
  { id: 7, name: "구로구" },
  { id: 8, name: "금천구" },
  { id: 9, name: "노원구" },
  { id: 10, name: "도봉구" },
  { id: 11, name: "동대문구" },
  { id: 12, name: "동작구" },
  { id: 13, name: "마포구" },
  { id: 14, name: "서대문구" },
  { id: 15, name: "서초구" },
  { id: 16, name: "성동구" },
  { id: 17, name: "성북구" },
  { id: 18, name: "송파구" },
  { id: 19, name: "양천구" },
  { id: 20, name: "영등포구" },
  { id: 21, name: "용산구" },
  { id: 22, name: "은평구" },
  { id: 23, name: "종로구" },
  { id: 24, name: "중구" },
  { id: 25, name: "중랑구" },
];

export const houses = [
  {
    title: "논현동 역세권 쉐하",
    houseID: 1,
    placeID: 1,
    placeName: "강남구",
    place: "서울시 강남구 논현동 34-2",
    gender: "여성전용",
    deposit: 100,
    rent: 35,
    imgPath:
      "https://cdn.ggumim.co.kr/cache/star/600/202105080042048JDlQZfKuR.jpeg",
  },
  {
    title: "신림역 역세권 쉐하",
    houseID: 2,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 신림동 626-65",
    gender: "남성전용",
    deposit: 200,
    rent: 45,
    imgPath:
      "https://blog.kakaocdn.net/dn/ba7rdD/btqyh0zZbTB/wLoKa4OJocFqbOOPuQ8CY0/img.png",
  },
  {
    title: "함께살아요",
    houseID: 3,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 신림로58길 62-5",
    gender: "여성전용",
    deposit: 150,
    rent: 32,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLpeLXRPW47ZNM29aAsRwGvqhOMm7ca_sI7A&usqp=CAU",
  },
  {
    title: "대학생 환영!",
    houseID: 4,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 청룡길 78",
    gender: "남성전용",
    deposit: 120,
    rent: 40,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShs_OMaLD7O97FWmWVqpOKcCdEAQClXKmz-A&usqp=CAU",
  },
  {
    title: "홍대 근처 직장인 쉐하",
    houseID: 5,
    placeID: 13,
    placeName: "마포구",
    place: "서울시 마포구 월드컵북로 31",
    gender: "여성전용",
    deposit: 110,
    rent: 25,
    imgPath:
      "https://cdn.ggumim.co.kr/cache/star/600/20220126164944uMvi9QEkS9.jpeg",
  },
  {
    title: "외국인도 거주가능!",
    houseID: 6,
    placeID: 13,
    placeName: "마포구",
    place: "서울시 마포구 독막로6길 14",
    gender: "남성전용",
    deposit: 170,
    rent: 17,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGSTH5hzy5sgVpt4sCGSSj8m8pIpyg0uub0g&usqp=CAU",
  },
  {
    title: "스프레틱스지롱",
    houseID: 7,
    placeID: 13,
    placeName: "마포구",
    place: "서울시 마포구 숭문4길 6",
    gender: "여성전용",
    deposit: 300,
    rent: 50,
    imgPath:
      "https://image.ohou.se/i/bucketplace-v2-development/uploads/projects/cover_images/1551338760020_CnahmbPF.jpg?gif=1&w=720",
  },
  {
    title: "살기좋은 후암동 하메구함",
    houseID: 8,
    placeID: 21,
    placeName: "용산구",
    place: "서울시 후암로 20",
    gender: "남성전용",
    deposit: 500,
    rent: 25,
    imgPath:
      "https://i.pinimg.com/1200x/7b/19/cc/7b19cc751ca9bccb151b3f2a6cfb44c8.jpg",
  },
  {
    title: "welcome",
    houseID: 9,
    placeID: 2,
    placeName: "강동구",
    place: "서울시 강동구 성내동 540",
    gender: "여성전용",
    imgPath:
      "https://contents-cdn.viewus.co.kr/image/230131/eebcdc29-620a-455d-be3e-6b9e9af82d9b.jpeg",
  },
  {
    title: "두명 입주 가능",
    houseID: 10,
    placeID: 6,
    placeName: "광진구",
    place: "서울시 광진구 아차산로 262",
    gender: "남성전용",
    imgPath:
      "https://cdn.ggumim.co.kr/cache/star/600/20220110171043YYfUggPqsx.jpg",
  },
  {
    title: "석촌호수 뷰 아파트입니다",
    houseID: 11,
    placeID: 18,
    placeName: "송파구",
    place: "서울시 송파구 올림픽로 35길 94",
    gender: "남성전용",
    imgPath:
      "https://dev-archisketch-resources.s3.ap-northeast-2.amazonaws.com/seesoop/v2/Interiorideas_HJ/1630984521_%EB%A6%AC%EB%B9%99%EB%A3%B8_%EC%A0%84%EC%B2%B4.jpg",
  },
  {
    title: "밥 제공합니다",
    houseID: 12,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 신림로 15길 31",
    gender: "남성전용",
    deposit: 120,
    rent: 40,
    imgPath:
      "https://t1.daumcdn.net/estate/interior/story/c53a89ba6b984d2584bd3abb75893805",
  },
  {
    title: "월세 30만원 ",
    houseID: 13,
    placeID: 5,
    placeName: "관악구",
    place: "서울시 관악구 신림로 374",
    gender: "남성전용",
    deposit: 120,
    rent: 40,
    imgPath: "https://t1.daumcdn.net/cfile/tistory/2258C048564B8E042A",
  },
  {
    title: "가로수길 10분컷 ",
    houseID: 14,
    placeID: 1,
    placeName: "강남구",
    place: "서울시 강남구 논현동 46-2",
    gender: "여성전용",
    deposit: 300,
    rent: 55,
    imgPath:
      "https://lh3.googleusercontent.com/sIjEoe2mdZP0QNYKAcAaKNIYnnKZBiqZ9EJPQMH6ID1KHm8Oe1Fk_j2noQU2FFyrGYB-LSbVJO27LdMyN88VRUss14gSO0DwrhqAmJv1FtysIuD2mA4iYEZwlTuSe3c85kDmVUmD1NDI0tZdGkPxe49ih91CHh3Dy_g-i_B2GAV5iJCHG2bea2AUaqCZdQ",
  },
  {
    title: "잠원중앞 아파트",
    houseID: 15,
    placeID: 15,
    placeName: "서초구",
    place: "서울시 서초구 잠원로 88",
    gender: "여성전용",
    deposit: 300,
    rent: 55,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgANQWfFaCS8r1E3Kz52BrhcNwLYmB-ow5Xg&usqp=CAU",
  },
];

export const favorite = [
  {
    title: "잠원중앞 아파트",
    houseID: 15,
    placeID: 15,
    placeName: "서초구",
    place: "서울시 서초구 잠원로 88",
    gender: "여성전용",
    deposit: 300,
    rent: 55,
    imgPath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgANQWfFaCS8r1E3Kz52BrhcNwLYmB-ow5Xg&usqp=CAU",
  },
  {
    title: "welcome",
    houseID: 9,
    placeID: 2,
    placeName: "강동구",
    place: "서울시 강동구 성내동 540",
    gender: "여성전용",
    imgPath:
      "https://contents-cdn.viewus.co.kr/image/230131/eebcdc29-620a-455d-be3e-6b9e9af82d9b.jpeg",
  },
];
